" ========================
" Plugin Manager (vim-plug)
" ========================

" Automatically install plugin manager if not installed
if empty(glob($MYVIMDIR . 'autoload/plug.vim'))
    silent execute '!curl -fLo '.$MYVIMDIR.'autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim'
    autocmd VimEnter * PlugInstall --sync | source $MYVIMRC
endif

call plug#begin()

" Plugins
Plug 'tpope/vim-fugitive'                           " Git Integration
Plug 'tpope/vim-vinegar'                            " Improved Netrw
Plug 'ap/vim-buftabline'                            " Buffer Bar
Plug 'itchyny/lightline.vim'                        " Status Line
Plug 'nordtheme/vim'                                " Nord Theme
Plug 'junegunn/fzf', { 'do': { -> fzf#install() } } " Fuzzy Finder
Plug 'junegunn/fzf.vim'                             " FZF Vim Integration
Plug 'neoclide/coc.nvim', { 'branch': 'release' }   " LSP & Autocompletion

call plug#end()

"Plug 'puremourning/vimspector' " Debugging
"Plug 'tpope/vim-obsession'     " Auto Session Saving
"Plug 'SirVer/ultisnips'        " Snippet Manager

" ========================
" Colorscheme
" ========================

set termguicolors
colorscheme nord

" ========================
" General Settings
" ========================

" Behavior
syntax enable           " Enable syntax highlighting
set nocompatible        " Disable Vi-compatible mode
set hidden              " Enable hidden (bg) buffers
set mouse=a             " Enable mouse support
set encoding=utf-8      " Use utf-8 encoding
set clipboard=unnamed   " Enabling system clipboard

" Line
set number              " Show line numbers
set linebreak           " Don't break in between words
set nofixeol            " Don't restore missing eol

" Undos, Backups & Swaps
set noswapfile          " Don't use swap files
set nobackup            " Don't use backup files
set nowritebackup       " Don't backup before overwrite

" Indents
set breakindent         " Continue indent on wrap
set autoindent          " Keep current indent on subsequent lines
set smartindent         " Guess and auto apply indents

" Scroll
set scrolloff=8         " Keep cursor 8 lines away from top/bottom
set sidescrolloff=8     " Keep cursor 8 lines away from left/right

" Search
set incsearch           " Live highlight matches
set hlsearch            " Highlight all matches
set ignorecase          " Case insensitive search
set smartcase           " Unless uppercase is used

" UI
set signcolumn=yes      " Always show signcolumn
set laststatus=2        " Enable status line
set cursorline          " Enable cursor line indicator
set wildmenu            " Enable command mode completions
set noshowmode          " Hide display mode below status bar
"set showcmd             " Show partial command

" Spaces and Tabs
set tabstop=4
set shiftwidth=4
set expandtab

" Performance
set updatetime=250
set timeoutlen=300

" Whitespace Characters
set list
set listchars=tab:»\ ,trail:·,extends:>,precedes:<,nbsp:␣

" Splits
set splitright
set splitbelow

" ========================
" Key Remaps
" ========================

" Space as leader
let mapleader = " "

" Split navigation
nnoremap <C-h> <C-w>h
nnoremap <C-j> <C-w>j
nnoremap <C-k> <C-w>k
nnoremap <C-l> <C-w>l

" Resize splits
nnoremap <S-Left> <C-w><
nnoremap <S-Down> <C-w>-
nnoremap <S-Up> <C-w>+
nnoremap <S-Right> <C-w>>

" Reposition cursor
nnoremap J mzJ`z
nnoremap <C-d> <C-d>zz
nnoremap <C-u> <C-u>zz
nnoremap n nzzzv
nnoremap N Nzzzv

" Misc
nnoremap // :noh<CR>
nnoremap Q :bdelete! %<CR>
nnoremap <leader>qq :q!<CR>

" ========================
" Plugin Configurations
" ========================

" Buftabline
let g:buftabline_numbers = 2
let g:buftabline_indicators = 1
nnoremap <S-L> :bnext<CR>
nnoremap <S-H> :bprev<CR>
nnoremap gb1 <Plug>BufTabLine.Go(1)
nnoremap gb2 <Plug>BufTabLine.Go(2)
nnoremap gb3 <Plug>BufTabLine.Go(3)
nnoremap gb4 <Plug>BufTabLine.Go(4)
nnoremap gb5 <Plug>BufTabLine.Go(5)
nnoremap gb6 <Plug>BufTabLine.Go(6)
nnoremap gb7 <Plug>BufTabLine.Go(7)
nnoremap gb8 <Plug>BufTabLine.Go(8)
nnoremap gb9 <Plug>BufTabLine.Go(9)
nnoremap gb0 <Plug>BufTabLine.Go(10)

" Lightline (this gets overwritten in coc-settings.vim if using CoC)
let g:lightline = { 'colorscheme': 'nord' }

" FZF
let g:fzf_vim = {}
let g:fzf_vim_preview_window = ['right,50%,<70(down,50%)']
let g:fzf_colors =
\ { 'fg':         ['fg', 'Normal'],
  \ 'bg':         ['bg', 'Normal'],
  \ 'preview-bg': ['bg', 'NormalFloat'],
  \ 'hl':         ['fg', 'Comment'],
  \ 'fg+':        ['fg', 'CursorLine', 'CursorColumn', 'Normal'],
  \ 'bg+':        ['bg', 'CursorLine', 'CursorColumn'],
  \ 'hl+':        ['fg', 'Statement'],
  \ 'info':       ['fg', 'PreProc'],
  \ 'border':     ['fg', 'Ignore'],
  \ 'prompt':     ['fg', 'Conditional'],
  \ 'pointer':    ['fg', 'Exception'],
  \ 'marker':     ['fg', 'Keyword'],
  \ 'spinner':    ['fg', 'Label'],
  \ 'header':     ['fg', 'Comment'] }
let $FZF_DEFAULT_OPTS = '--bind=ctrl-u:preview-half-page-up,ctrl-d:preview-half-page-down'
nnoremap <Leader>ff :Files<CR>|   " Find files
nnoremap <Leader>fb :Buffers<CR>| " Find buffers
nnoremap <Leader>fr :History<CR>| " Find recent files
nnoremap <Leader>fh :Help<CR>|    " Find help tags
nnoremap <Leader>ft :GFiles<CR>|  " Search git tracked files
nnoremap <Leader>fc :GFiles?<CR>| " Search git changed files
nnoremap <Leader>fg :Rg<CR>|      " Live grep project directory
nnoremap <Leader>fl :BLines<CR>|  " Grep lines in current buffer

" CoC Settings
" For adding new lsps:
"   1 - add in coc_global_extensions list
"   2 - add filetype in coc-settings.vim @ line 84 (setting up formatexpr)
let g:coc_global_extensions = ['coc-git', 'coc-vimlsp', 'coc-json', 'coc-sh', 'coc-java', 'coc-pyright']
" Source coc vim settings if it exists
if filereadable(expand('$XDG_CONFIG_HOME/vim/coc-settings.vim'))
  source $XDG_CONFIG_HOME/vim/coc-settings.vim
endif

" Vinegar (default bindings)
"   gh : toggle hidden files
"   ~  : go to home directory
"   -  : go up the file tree
"   .  : pre populate path at the end of command mode
"   y  : yank absolute path

" Start Obsession (Auto session saving)
" autocmd VimEnter * Obsession

" TODO: auto bracket pairs (reproduce issue first)
" TODO: replace vinegar with nerdtree
" TODO: broken snippet behavior (probably needs coc-snippets or ultisnips)
" TODO: custom minimal start screen
" TODO: coc-git bindings
"           blame
"           chunk info
"           next/prev chunk
"           open current line in browser
"           copy permalink of current line
