#!/usr/bin/env bash

# exit if no file is passed
if [[ -z "$1" ]]; then
  echo "no file selected"
  exit 1
fi

# check if the file is a text-based file (contains 'text' in mime type)
mime_type=$(file --mime-type "$1" | cut -d ':' -f2)
if [[ "$mime_type" =~ text ]]; then
  vim "$1"
else
  open "$1"
fi
