[general]
    import = [
        # colorschemes @ https://github.com/alacritty/alacritty-theme
        # warm : doom_one, gruvbox_material_hard_dark
        # cool : nord, nightfox, ayu_mirage, horizon_dark
        "~/.config/alacritty/themes/themes/nord.toml",
    ]
[window]
    dynamic_padding = true
    padding = { x = 16, y = 10 }
    decorations = "Buttonless"
    resize_increments = true
[font]
    # brew install font-jetbrains-mono-nerd-font
    normal = { family = "JetBrainsMono Nerd Font", style = "Regular" }
    size = 15
[[hints.enabled]]
    command = "open"
    hyperlinks = true
    post_processing = true
    persist = false
    mouse.enabled = true
    binding = { key = "O", mods = "Command|Shift" }
    regex = "(ipfs:|ipns:|magnet:|mailto:|gemini://|gopher://|https://|http://|news:|file:|git://|ssh:|ftp://)[^\u0000-\u001F\u007F-\u009F<>\"\\s{-}\\^⟨⟩`\\\\]+"


# vi mode - cmd + shift + space
[[keyboard.bindings]]
    key = "Space"
    mods = "Command|Shift"
    mode = "~Search"
    action = "ToggleViMode"
[[keyboard.bindings]]
    key = "Space"
    mods = "Control|Shift"
    mode = "~Search"
    action = "None"

[[keyboard.bindings]]
    key = "k"
    mods = "Command"
    mode = "~Vi"
    action = "ScrollLineUp"
[[keyboard.bindings]]
    key = "j"
    mods = "Command"
    mode = "~Vi"
    action = "ScrollLineDown"
